/**
 * Actions types
 */

export enum SimulationActionsTypesEnum {
    UPDATE_JOB,
    UPDATE_HOUSING,
    UPDATE_TRANSPORTATION,
    UPDATE_HEALTH,
    UPDATE_MISCHELLANEOUS,
    LOAD_INITIAL_PIE_CHART,
    UPDATE_PIE_CHART,
    UPDATE_CONTENT,
    SAVE,
    RESET,
    LOAD_FROM_LOCAL_STORAGE,
    CLEAR
}
