/**
 * Actions types
 */

export enum SimulationActionsTypesEnum {
    SELECT_JOB,
    SELECT_HOUSING,
    SELECT_COMMUTE_MODE,
    SET_HOUSING_EXPENSE,
    SET_COMMUTE_EXPENSE,
    SET_GAS_EXPENSE,
    SET_MAINTENANCE,
    SET_HEALTH_EXPENSE,
    SET_MISCHELLANEOUS,
    SET_YES_OR_NO,
    LOAD_INITIAL_PIE_CHART,
    SELECT_HEALTH,
    UPDATE_PIE_CHART,
    UPDATE_CONTENT,
    SAVE,
    RESET,
    LOAD_FROM_LOCAL_STORAGE,
    CLEAR
}
